"""Add email to employees

Revision ID: 4d0f1f575175
Revises: 5b0da6d84151
Create Date: 2026-09-28 16:48:47.513966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0f1f575175'
down_revision: Union[str, Sequence[str], None] = '5b0da6d84151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint("uq_employees_email", 'employees', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("uq_employees_email", 'employees', type_='unique')
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
